### ISSUE TITLE
Selecting all rows of a data-frame where a given column is equal to a given value

### ISSUE THREAD

**Issue by Mawandaian** [vega/datalib#103]
I want to select all rows where a column is equal to a given value, eg where sex = 'male', but I have failed to find the datalib function to help me do it.

**Comment by jheer** [comment]
Datalib "tables" are simply arrays of JavaScript objects. So you can use standard [array methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array), such as [`filter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) or [`find`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find).
