### ISSUE TITLE
Add note to docs that Datalib is not maintained

### ISSUE THREAD

**Issue by alexkreidler** [vega/datalib#110]
I came here searching for some details on Vega's CSV parsing, and only found out from the below issue that Vega doesn't use that functionality from this library any more: 

> We don't actively maintain datalib anymore (functionality is now provided by Vega dataflow and transforms). Having said that, we would be delighted to review pull requests.

_Originally posted by @domoritz in https://github.com/vega/datalib/issues/100#issuecomment-451982242_

It would be great to add a note to the README to indicate that the library is not maintained, and add a link to the relevant bits of Vega/Vega-Lite code that replace it. 

Thanks!

**Comment by jheer** [comment]
Done, thanks!
