### ISSUE TITLE
Feature request: can left- rigth, etc., "joins" be implemented ?

### ISSUE THREAD

**Issue by dan-reznik** [vega/datalib#111]

**Comment by jheer** [comment]
Datalib is no longer being actively developed, so new feature requests are unlikely to be met.

However, you may want to take a look at its successor [arquero](https://github.com/uwdata/arquero), which includes most of datalib's functionality and much more, including support for joins.

**Comment by dan-reznik** [comment]
I just saw this today. It may make sense to add your comment to the main
page on datalib.

**Comment by jheer** [comment]
Done, thanks!
