### ISSUE TITLE
Why does `dl.date` return a unix timestamp?

### ISSUE THREAD

**Issue by domoritz** [vega/datalib#39]
I was wondering why the datalib method `dl.date` returns a unix timestamp rather than a `Date()` object. 

```js
> dl.date('2015')
1420099200000
> new Date(dl.date('2015'))
Thu Jan 01 2015 00:00:00 GMT-0800 (PST)
```

**Comment by jheer** [comment]
In part to avoid object invocation overhead until absolutely necessary (think datasets with 100k rows). Datalib operations are also (or at minimum, should be) timestamp-smart.
