### ISSUE TITLE
Automatic number format for large ranges uses the same precision prefix

### ISSUE THREAD

**Issue by domoritz** [vega/datalib#42]
I don;t know what the intended behavior of auto formatting is but I found that datalib formats large ranges with the same precision prefix (e.g. `M` for million)

```js
> a = [0,1,10,100,1000,10000, 100000, 1000000]; f = dl.format.auto.number(a, 1, 's'); a.map(f)
["0M", "0M", "0M", "0M", "0M", "0M", "0M", "1M"]
```

I would expect to get something similar to what this code produces (minus the `0m`, which should just be 0).

```js
a = [0,1,10,100,1000,10000, 100000, 1000000]; a.map(function(d) { return dl.format.auto.number([d], 1, 's')(d); })
> ["0m", "1", "10", "100", "1k", "10k", "100k", "1M"]
```

I'm not sure whether I am misunderstanding the intended behavior of the function.

**Comment by jheer** [comment]
Fixed in c4c904f. Will be included in datalib 1.4.7 release.
