### ISSUE TITLE
Separate standalone utils methods in util.js from methods that depend on other libraries

### ISSUE THREAD

**Issue by kanitw** [vega/datalib#60]
Some methods in `util.js` depends on `d3-time` and `buffer`.    
Since we are requiring `util.js`in Vega-LIte but we do not use d3-time or buffer.  This leads to larger compiled file size in Vega-Lite.  From a conversation with @jheer, we agree that methods that depend on other libraries should be splitted.

**Comment by jheer** [comment]
Done as of 494d764ac46acb41a4f517835d73f66ae9741b76, and released in v1.5.8.
