### ISSUE TITLE
Format "date:'%H:%M'" results in Error: Format pattern must be quoted: '%H

### ISSUE THREAD

**Issue by Jerrythafast** [vega/datalib#68]
Dear devs,

Got a small issue with time value parsing in Vega.
This works:
```js
dl.read([{"a": "13h15"}], {parse: {a: "date:'%Hh%M'"}});
```
Gives:
```js
[{a: new Date(...)}]
```

But this does not work:
```js
dl.read([{"a": "13:15"}], {parse: {a: "date:'%H:%M'"}});
```
Gives:
> Error: Format pattern must be quoted: '%H

I bet it's got something to do with the colon :wink:

Kind regards,
Jerry

EDIT: Corrected API calls as per comment of @domoritz below.

**Comment by domoritz** [comment]
I think the problem is https://github.com/vega/datalib/blob/master/src/import/read.js#L21.

**Comment by domoritz** [comment]
We need to get this working `dl.read([{"a": "13:15"}], {parse: {a: "date:'%H:%M'"}});`
