### ISSUE TITLE
Support standard error

### ISSUE THREAD

**Issue by kanitw** [vega/datalib#71]
@ayush29feb   You might wanna look at this folder: https://github.com/vega/datalib/tree/master/src/aggregate to add standard error.

**Comment by domoritz** [comment]
Why do we need this? Isn't it just a combination of stdev and count?

**Comment by kanitw** [comment]
Yes, but you want to support that as a part of aggregate transform without introducing macro (to convert `stderr` to a part of `aggregate` and `formula` transforms, the natural place to support that is here.   

If you use this argument, `mean` is a combination of `sum` and `count` as well.

**Comment by jheer** [comment]
Added in aba8d3f443b94087173eed6050c6ba2aaeb14747.

**Comment by kanitw** [comment]
Thank you @jheer.
