### ISSUE TITLE
We need to do some math in templates to support quarters in Vega-Lite

### ISSUE THREAD

**Issue by domoritz** [vega/datalib#72]
@bobocandys would like to show quarters in Vega-Lite.

To format dates, we use datalib templates. We automatically generate template strings that look like:

`Q{{datum.data | time:'%m' | quarter}}{{datum.data | time:'-%B'}}`

The problem with `datum.data | time:'%m' | quarter` is that `%m` is in the range [1,12]  but quarter expects [0,11]. We could either

a) Change the behavior of the `quarter` template filter
b) Support expressions in templates such as `expr:"x/12+3"`. This would actually allow us to remove the `quarter` filter because it's a simple expression. However, this means we would have to add vega-expression as a dependency.
c) Add a decrement filter to datalib :-(
d) Add a way to call the `getMonth` method on the date (which returns a number for the month in the range of [0,11]).

**Comment by domoritz** [comment]
https://github.com/vega/vega-lite/pull/1305

**Comment by jheer** [comment]
Piping through month to quarter does seem odd. I think we should just re-write the quarter filter to expect a datetime value as input, just like the other datetime format methods. I can get to this at some point, but in the meantime you should feel free to make the change yourselves and submit a PR.

**Comment by domoritz** [comment]
Yeah, I had that implemented at first (https://github.com/vega/datalib/pull/67/commits/9d659cb2bdb249423819a0b1f7a880f604217b79) but then we need one version for UTC and one without. We will send a pr with the two filters.

**Comment by domoritz** [comment]
Pr in https://github.com/vega/datalib/pull/73
