### ISSUE TITLE
Why is `weekdays` as a time bin unit pluralized? 

### ISSUE THREAD

**Issue by kanitw** [vega/datalib#78]
From https://github.com/vega/datalib/wiki/Statistics#dl_bins_date,
all singular time unit refers to single-part time units 
while all plural time units refer to multi-part time units except "weekdays".  

Not sure if there is a reason for this?

**Comment by kanitw** [comment]
(Besides, it's worth noting that our time unit in datalib and Vega-Lite are vastly different.  We might consider revising to consolidate.)

**Comment by kanitw** [comment]
I see.  Actually plural = period time units.

**Comment by domoritz** [comment]
> Besides, it's worth noting that our time unit in datalib and Vega-Lite are vastly different.

Can you elaborate?

**Comment by domoritz** [comment]
I think this is what you meant https://github.com/vega/vega-lite/issues/1487
