### ISSUE TITLE
Fix failing build

### ISSUE THREAD

**Issue by curran** [vega/datalib#88]
The CI build is currently failing:

![image](https://user-images.githubusercontent.com/68416/32371305-5888cc7e-c0b6-11e7-8f66-57edfb1d9a58.png)

**Comment by domoritz** [comment]
It's because of hawk using `const`, which is not supported in node 0.12.

**Comment by curran** [comment]
In that case, probably this can be solved by simply updating the Node version in `travis.yml`.

See https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Specifying-Node.js-versions

**Comment by curran** [comment]
@domoritz Hey it worked! https://github.com/vega/datalib/pull/89

**Comment by domoritz** [comment]
See #93
