### ISSUE TITLE
Support for non-US dates.

### ISSUE THREAD

**Issue by mfds** [vega/datalib#92]
Hello, is there any way to infer a non US style date?

```javascript
> dl.type.infer(['25/01/2016'])
"string"
> dl.type.infer(['01/25/2016'])
"date"
```

Perhaps I didn't check enough but I didn't see anything related to locale or similar inside the documentation.

Thanks,
M.

**Comment by jheer** [comment]
The default date parser / type checker is simply JavaScript's built-in [Date.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse). Unfortunately, this method is not standardized and so can vary across JavaScript runtimes and browsers. Moreover, datalib does not currently provide a way to extend type inference with custom type checks.

That said, if you know that a field should contain a date and you know the proper format, you can provide a _format_ parameter to [`dl.read`](https://github.com/vega/datalib/wiki/Import#dl_read) to parse the date values. For example, you might run `dl.type.inferAll` and then overwrite the value for the date field with a custom entry:

```js
var types = dl.type.inferAll(table);
type.dateField = 'date:<format-string>';
```

Also, FWIW documentation for locales is here:
https://github.com/vega/datalib/wiki/Formatting#Locales

However, this concerns defaults for output formatting, not parsing.
